In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
from pandas.api.types import CategoricalDtype
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix

# !pip install openpyxl

pd.set_option('display.max_rows', 50)

# New section

In [2]:
songs = pd.read_excel("spotify_genre_final.xlsx")

In [3]:
songs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6917 entries, 0 to 6916
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Genre                   6917 non-null   object 
 1   Title                   6917 non-null   object 
 2   Album_cover_link        6917 non-null   object 
 3   Artist                  6917 non-null   object 
 4   duration_ms             6917 non-null   int64  
 5   explicit                6917 non-null   bool   
 6   id                      6917 non-null   object 
 7   popularity              6917 non-null   int64  
 8   release_date            6917 non-null   object 
 9   release_date_precision  6917 non-null   object 
 10  total_tracks            6917 non-null   int64  
 11  danceability            6917 non-null   float64
 12  energy                  6917 non-null   float64
 13  key                     6917 non-null   int64  
 14  loudness                6917 non-null   

In [4]:
songs_by_genre = songs.groupby("Genre")
songs_by_artist = songs.groupby("Artist")

In [5]:
artists = []
for artist, songs in songs_by_artist:
    artists.append(artist)

In [6]:
genres = []
for genre, songs_group in songs_by_genre:
  genres.append(genre)
  print(genre)
  display(songs_group)

edm


Genre                           Title  \
2062   edm                            Hero   
2063   edm  Real Love (feat. Aleyna Tilki)   
2064   edm                    Gotta Be You   
2065   edm                            Okay   
2066   edm                      Worst Case   
...    ...                             ...   
3013   edm                        Break Me   
3014   edm                  Shiawase - VIP   
3015   edm       Left Behinds - Radio Edit   
3016   edm                         R.E.A.L   
3017   edm                            Am I   

                                       Album_cover_link          Artist  \
2062  https://i.scdn.co/image/ab67616d0000b27368c134...        Afrojack   
2063  https://i.scdn.co/image/ab67616d0000b2738fe23c...  Dillon Francis   
2064  https://i.scdn.co/image/ab67616d0000b27329204e...           NERVO   
2065  https://i.scdn.co/image/ab67616d0000b2737dd8c5...    Nicky Romero   
2066  https://i.scdn.co/image/ab67616d0000b273380a16...            3LAU   
...                                                 ...             ...   
3013  https://i.scdn.co/image/ab67616d0000b273c3bbe6...        Trivecta   
3014  https://i.scdn.co/image/ab67616d0000b273d1dcf9...     Dion Timmer   
3015  https://i.scdn.co/image/ab67616d0000b2737fff2e...     Paris Blohm   
3016  https://i.scdn.co/image/ab67616d0000b273389ba0...       Dombresky   
3017  https://i.scdn.co/image/ab67616d0000b2734717ec...      Deniz Koyu   

      duration_ms  explicit                      id  popularity release_date  \
2062       171840     False  29p6UW08MXzwj9thWBW3uF          73   2021-04-30   
2063       135265     False  7BxIvkfVSgoUUlDcBVff61          48   2021-10-05   
2064       149032     False  2Q8fFORnsDE6I3RNvSLXSf          67   2021-01-08   
2065       151312     False  1muUz481pBOMzJ9De3NS6e          33   2021-09-10   
2066       178048     False  3zbbRebB1rzlXJgq7Ufn8V          62   2021-10-08   
...           ...       ...                     ...         ...          ...   
3013       222631     False  3cjkfbF4rgqymxtRn7Iv15          43   2017-07-03   
3014       181750     False  4mTLnLuHoGhA2xd595OMg1          47   2020-09-09   
3015       180014     False  2Lmk4VmhPzw6fw3kvKmmUe          23   2014-08-04   
3016       183095     False  1mK6vQxrBu7tStp3b8G2Z9          53   2021-10-15   
3017       163603     False  0QsI3ajMaHkyXqgg6XPWqj          40   2021-11-05   

     release_date_precision  ...  key  loudness  mode  speechiness  \
2062                    day  ...    2    -5.032     1       0.0313   
2063                    day  ...   10    -4.313     0       0.0685   
2064                    day  ...    6    -5.271     0       0.0452   
2065                    day  ...    2    -3.781     1       0.0579   
2066                    day  ...    6    -5.775     0       0.0339   
...                     ...  ...  ...       ...   ...          ...   
3013                    day  ...   11    -4.150     0       0.1680   
3014                    day  ...    8    -0.563     1       0.1540   
3015                    day  ...    8    -4.051     0       0.1520   
3016                    day  ...    0    -3.240     1       0.0741   
3017                    day  ...   11    -4.156     1       0.0423   

      acousticness  instrumentalness  liveness  valence    tempo  \
2062       0.15700          0.000000    0.1530    0.523  125.001   
2063       0.04960          0.000085    0.0522    0.555  124.012   
2064       0.25200          0.028800    0.0708    0.376  123.910   
2065       0.04630          0.000000    0.1280    0.304  124.964   
2066       0.00463          0.034700    0.2050    0.177  122.975   
...            ...               ...       ...      ...      ...   
3013       0.04980          0.000003    0.3460    0.463   75.995   
3014       0.00612          0.000176    0.6650    0.500  150.096   
3015       0.00185          0.033100    0.1430    0.155  128.027   
3016       0.00106          0.834000    0.0348    0.768  126.003   
3

hiphop


Genre                       Title  \
5215  hiphop              Can I Kick It?   
5216  hiphop              Hip Hop Hooray   
5217  hiphop               Ms. Fat Booty   
5218  hiphop   Don't Sweat The Technique   
5219  hiphop               Passin' Me By   
...      ...                         ...   
6181  hiphop              I'm A Swing It   
6182  hiphop                   Here I Go   
6183  hiphop               One Call Away   
6184  hiphop  Spontaneous - 13 MC's Deep   
6185  hiphop             The I.N.C. Ride   

                                       Album_cover_link  \
5215  https://i.scdn.co/image/ab67616d0000b2734ba1fe...   
5216  https://i.scdn.co/image/ab67616d0000b27393e4dd...   
5217  https://i.scdn.co/image/ab67616d0000b27389b56f...   
5218  https://i.scdn.co/image/ab67616d0000b273d55241...   
5219  https://i.scdn.co/image/ab67616d0000b2739ec4ab...   
...                                                 ...   
6181  https://i.scdn.co/image/ab67616d0000b273fdfb1a...   
6182  https://i.scdn.co/image/ab67616d0000b2736d7a08...   
6183  https://i.scdn.co/image/ab67616d0000b273f9aefc...   
6184  https://i.scdn.co/image/ab67616d0000b273ec8d44...   
6185  https://i.scdn.co/image/ab67616d0000b273ead341...   

                         Artist  duration_ms  explicit  \
5215       A Tribe Called Quest       251573     False   
5216          Naughty By Nature       267266     False   
5217                    Mos Def       223546      True   
5218            Eric B. & Rakim       262800     False   
5219               The Pharcyde       303493     False   
...                         ...          ...       ...   
6181              House Of Pain       223800      True   
6182                   Mystikal       345066      True   
6183                     Chingy       276800     False   
6184  Leaders of the New School       279173      True   
6185     Masta Ace Incorporated       250266      True   

                          id  popularity release_date release_date_precision  \
5215  3Ti0GdlrotgwsAVBBugv0I          70   1990-04-17                    day   
5216  1w29UTa5uUvIri2tWtZ12Y          66   1993-02-23                    day   
5217  0IVAlb0cFCH1cQ974iR1TU          70   1999-10-12                    day   
5218  48ZUwXrEOhaXLCxvmRYhZv          62   1992-01-01                    day   
5219  4G3dZN9o3o2X4VKwt4CLts          69   1992-11-24                    day   
...                      ...         ...          ...                    ...   
6181  4Zgl65eYgR2WhvGDGlv2mz          48         1994                   year   
6182  0Sizq91V0brNa9RBpMfeOB          48   1995-10-09                    day   
6183  0UNTBB02C1aB55Fu4H63qd          62   2003-01-01                    day   
6184  0CMO9nOUMmpJ1SBgvglfMa          28   1993-09-21                    day   
6185  37iYAAUVZezZRmgTGnWbhY          42   1995-01-01                    day   

      ...  key  loudness  mode  speechiness  acousticness  instrumentalness  \
5215  ...    0    -6.547     1       0.2740       0.17300          0.000699   
5216  ...    6   -13.652     0       0.1010       0.10200          0.000000   
5217  ...    1    -4.827     1       0.1890       0.14800          0.000000   
5218  ...    4    -8.443     1       0.1580       0.00556          0.001710   
5219  ...    4    -8.145     0       0.2660       0.09030          0.000002   
...   ...  ...       ...   ...          ...           ...               ...   
6181  ...   11   -10.184     1       0.1200       0.01220          0.004550   
6182  ...    6    -4.992     0       0.0731       0.35500          0.000000   
6183  ...    4    -5.926     0       0.1830       0.09180          0.000000   
6184  ...    7   -12.636     1       0.3390       0.30800          0.000036   
6185  ...   11    -8.509     0       0.0485       0.07750          0.312000   

      liveness  valence    tempo  time_signature  
5215    0.1290    0.744   96.662               4  
5216    0.2720    0.765   99.201               4  
5217    0

latin


Genre                      Title  \
3018  latin                      Volví   
3019  latin               Fiel - Remix   
3020  latin         Andas En Mi Cabeza   
3021  latin  Otra vez (feat. J Balvin)   
3022  latin              Quiero Bailar   
...     ...                        ...   
4049  latin                   Desnudos   
4050  latin             Amor Escondido   
4051  latin        Que Levante la Mano   
4052  latin                 Tu Secreto   
4053  latin            Mi Bebe - Remix   

                                       Album_cover_link            Artist  \
3018  https://i.scdn.co/image/ab67616d0000b27312bcec...          Aventura   
3019  https://i.scdn.co/image/ab67616d0000b2737725ef...             Wisin   
3020  https://i.scdn.co/image/ab67616d0000b2736df5cc...     Chino & Nacho   
3021  https://i.scdn.co/image/ab67616d0000b27382eabf...     Zion & Lennox   
3022  https://i.scdn.co/image/ab67616d0000b2738666a2...         Ivy Queen   
...                                                 ...               ...   
4049  https://i.scdn.co/image/ab67616d0000b27380513c...  Daniel Santacruz   
4050  https://i.scdn.co/image/ab67616d0000b2734caf83...           Cruzito   
4051  https://i.scdn.co/image/ab67616d0000b2730bc136...    Joseph Fonseca   
4052  https://i.scdn.co/image/ab67616d0000b27347d42f...    Elvis Martinez   
4053  https://i.scdn.co/image/ab67616d0000b2736f64c9...        Baby Ranks   

      duration_ms  explicit                      id  popularity release_date  \
3018       230125      True  2vmfvSoZBFAt9hhRoEByLi          91   2021-08-03   
3019       349546      True  43qcs9NpJhDxtG91zxFkj7          83   2021-06-15   
3020       247493     False  23WI5V2eD4EyGKxSl7Pyeq          74   2016-02-19   
3021       209453     False  3QwBODjSEzelZyVjxPOHdq          75   2016-09-30   
3022       184506     False  1EyH5BK5Cx5XzQyEDks0fT          61   2004-01-01   
...           ...       ...                     ...         ...          ...   
4049       198000     False  2bqv853XoPpL6tEzr40pfE          46   2018-05-25   
4050       210000     False  7icnNUsk49I1aa9lfJ9bB5          21   2018-06-12   
4051       237560     False  4mPgxlYJlHWiy5BrzKxBe1          46   2002-01-01   
4052       211226     False  4AKtpixRxtQQhy7OCYJbhL          41   2000-05-01   
4053       182946     False  3xqzyI3n74PvzpiEMdJarl          27   2020-10-12   

     release_date_precision  ...  key  loudness  mode  speechiness  \
3018                    day  ...    1    -3.726     1       0.1820   
3019                    day  ...    6    -4.733     0       0.0473   
3020                    day  ...    9    -1.870     1       0.1300   
3021                    day  ...   10    -5.429     1       0.1000   
3022                    day  ...    5    -5.261     1       0.0951   
...                     ...  ...  ...       ...   ...          ...   
4049                    day  ...    3    -5.258     0       0.0482   
4050                    day  ...    9    -8.753     0       0.0492   
4051                    day  ...    5    -4.116     0       0.0379   
4052                    day  ...   11    -6.661     1       0.0519   
4053                    day  ...    0    -2.605     1       0.1490   

      acousticness  instrumentalness  liveness  valence    tempo  \
3018        0.4220          0.000284    0.0674    0.791  175.896   
3019        0.3980          0.000002    0.1180    0.573   97.990   
3020        0.0244          0.000000    0.1110    0.556  104.114   
3021        0.0559          0.000486    0.4400    0.704   96.016   
3022        0.3000          0.000000    0.2940    0.737   95.027   
...            ...               ...       ...      ...      ...   
4049        0.4550          0.002300    0.3830    0.900  129.982   
4050        0.0421          0.000047    0.2780    0.670   89.951   
4051        0.3430          0.000107    0.2530    0.923  119.937   
4052        0.0893          0.000007    0.1370    0.965  129.926   
4053        0.1980        

pop


Genre                                    Title  \
4054   pop                             Don't Go Yet   
4055   pop          What A Time (feat. Niall Horan)   
4056   pop                  Scars To Your Beautiful   
4057   pop  Dusk Till Dawn (feat. Sia) - Radio Edit   
4058   pop                                 Reckless   
...    ...                                      ...   
5210   pop                           Loved You Once   
5211   pop                                   Moment   
5212   pop      Still the Same (feat. Boy In Space)   
5213   pop              Sway With Me (with GALXARA)   
5214   pop                         Confidently Lost   

                                       Album_cover_link           Artist  \
4054  https://i.scdn.co/image/ab67616d0000b273d24bb6...   Camila Cabello   
4055  https://i.scdn.co/image/ab67616d0000b2737e7069...   Julia Michaels   
4056  https://i.scdn.co/image/ab67616d0000b273e3ae59...     Alessia Cara   
4057  https://i.scdn.co/image/ab67616d0000b2732bdcb3...             ZAYN   
4058  https://i.scdn.co/image/ab67616d0000b273fe32f3...     Madison Beer   
...                                                 ...              ...   
5210  https://i.scdn.co/image/ab67616d0000b27316a9f3...        Clara Mae   
5211  https://i.scdn.co/image/ab67616d0000b27350aa87...   Victoria Monét   
5212  https://i.scdn.co/image/ab67616d0000b273f212e1...       SHY Martin   
5213  https://i.scdn.co/image/ab67616d0000b2730ec957...         Saweetie   
5214  https://i.scdn.co/image/ab67616d0000b273ca1582...  Sabrina Claudio   

      duration_ms  explicit                      id  popularity release_date  \
4054       164842     False  1058fW9H3fZA6QjYCdOBad          88   2021-07-23   
4055       173306     False  5WtfUKzXircvW8l5aaVZWT          84   2019-01-24   
4056       230226     False  0prNGof3XqfTvNDxHonvdK          73   2015-11-13   
4057       239000     False  3e7sxremeOE3wTySiOhGiP          76   2018-12-14   
4058       203384     False  5ajjAnNRh8bxFvaVHzpPjh          83   2021-06-04   
...           ...       ...                     ...         ...          ...   
5210       148603     False  6cc7nzmG4iClAyl47BOf2Z          55   2020-08-28   
5211       179413      True  6rSUrh8ErKSKfbH0t0IzCM          62   2020-08-07   
5212       178139     False  0f8xPdFJ6SdlHJwkxpdw2Q          61   2020-02-28   
5213       168018     False  5gqLY5H1ZyT3BScVr0nDMs          63   2020-01-31   
5214       209885     False  3cQmqM0awej9iAESjhKrI9          61   2017-03-02   

     release_date_precision  ...  key  loudness  mode  speechiness  \
4054                    day  ...   10    -6.967     0       0.1030   
4055                    day  ...    0    -6.184     1       0.0302   
4056                    day  ...    0    -5.740     1       0.1290   
4057                    day  ...   11    -6.589     0       0.0386   
4058                    day  ...    3    -6.642     1       0.0363   
...                     ...  ...  ...       ...   ...          ...   
5210                    day  ...    4    -5.988     1       0.0420   
5211                    day  ...    1    -8.889     1       0.0547   
5212                    day  ...    4    -7.632     1       0.0463   
5213                    day  ...    3    -4.243     0       0.0489   
5214                    day  ...    5    -8.575     1       0.0838   

      acousticness  instrumentalness  liveness  valence    tempo  \
4054       0.04920          0.000000    0.0442   0.6100  110.108   
4055       0.66200          0.000000    0.0853   0.3860  132.861   
4056       0.02850          0.000000    0.1110   0.4510   97.085   
4057       0.10200          0.000001    0.1060   0.0951  180.042   
4058       0.80700          0.000000    0.1400   0.2610  180.104   
...            ...               ...       ...      ...      ...   
5210       0.65500          0.000000    0.1570   0.3080   77.732   
5211       0.63700          0.005240    0.1220   0.3610  130.111   
5212       0.3670

r&b


Genre                   Title  \
6186   r&b            When I See U   
6187   r&b                    Love   
6188   r&b           Angel of Mine   
6189   r&b  Officially Missing You   
6190   r&b   Pick Up Your Feelings   
...    ...                     ...   
6912   r&b                  Moment   
6913   r&b        If I Was the One   
6914   r&b            I Don't Care   
6915   r&b             Complicated   
6916   r&b                Innocent   

                                       Album_cover_link            Artist  \
6186  https://i.scdn.co/image/ab67616d0000b273484cce...          Fantasia   
6187  https://i.scdn.co/image/ab67616d0000b2732cc232...      Keyshia Cole   
6188  https://i.scdn.co/image/ab67616d0000b273fb8bce...            Monica   
6189  https://i.scdn.co/image/ab67616d0000b273738910...             Tamia   
6190  https://i.scdn.co/image/ab67616d0000b273293ac9...  Jazmine Sullivan   
...                                                 ...               ...   
6912  https://i.scdn.co/image/ab67616d0000b27350aa87...   Victoria Monét   
6913  https://i.scdn.co/image/ab67616d0000b2733abb01...         Ruff Endz   
6914  https://i.scdn.co/image/ab67616d0000b273436ead...       Elle Varner   
6915  https://i.scdn.co/image/ab67616d0000b273dc377a...       Leela James   
6916  https://i.scdn.co/image/ab67616d0000b2733cb656...      Justine Skye   

      duration_ms  explicit                      id  popularity release_date  \
6186       217346     False  4iuNZTcvT9diFySSzVsnVS          70   2006-12-09   
6187       255333     False  0W4NhJhcqKCqEP2GIpDCDq          74   2005-01-01   
6188       250173     False  1AM1o0mKbgAK5oMpY8B3Z7          66   1998-07-13   
6189       242466     False  4IFYR5smTnHYCLP82AiDrJ          55         2004   
6190       229413     False  2I7CJZLo2nDqGuzZJA1XlZ          61   2021-01-07   
...           ...       ...                     ...         ...          ...   
6912       179413      True  6rSUrh8ErKSKfbH0t0IzCM          62   2020-08-07   
6913       266866     False  1iNO6V1JBTSy9aaiLrOHkZ           1   2000-07-22   
6914       186466     False  6PxzCYqI60zgJLxxgs1vme          34   2012-08-03   
6915       244870     False  4qkAApWcCWyhDvQ5d1fsUc          46   2021-07-30   
6916       173341      True  7A1xtIabfrZ5X3xIa7KqWj          47   2021-06-25   

     release_date_precision  ...  key  loudness  mode  speechiness  \
6186                    day  ...    8    -6.486     1       0.1720   
6187                    day  ...    5    -4.285     1       0.0283   
6188                    day  ...   10    -6.869     0       0.0239   
6189                   year  ...    4    -9.239     0       0.0368   
6190                    day  ...    2    -6.239     0       0.0464   
...                     ...  ...  ...       ...   ...          ...   
6912                    day  ...    1    -8.889     1       0.0547   
6913                    day  ...   10    -7.189     1       0.0335   
6914                    day  ...    9    -4.746     1       0.2110   
6915                    day  ...    8    -5.287     1       0.1310   
6916                    day  ...    0    -8.568     0       0.1100   

      acousticness  instrumentalness  liveness  valence    tempo  \
6186       0.45200          0.000079    0.2050    0.754   93.135   
6187       0.06400          0.000000    0.1000    0.318  116.714   
6188       0.00373          0.000032    0.2230    0.208   90.160   
6189       0.24700          0.000000    0.1440    0.226  178.258   
6190       0.32100          0.000000    0.1170    0.599   85.460   
...            ...               ...       ...      ...      ...   
6912       0.63700          0.005240    0.1220    0.361  130.111   
6913       0.36800          0.000000    0.0972    0.298  111.832   
6914       0.09010          0.000000    0.1640    0.578   84.917   
6915       0.06290          0.000002    0.0616    0.740  139.980   
6916       0.13000          0.000009    0.1750    0.195   89.347   

    

rap


Genre                                          Title  \
1136   rap                                  Unforgettable   
1137   rap  Sharing Locations (feat. Lil Baby & Lil Durk)   
1138   rap                             Wake Up in the Sky   
1139   rap                                     Plain Jane   
1140   rap                                 Collard Greens   
...    ...                                            ...   
2057   rap                                         Ninety   
2058   rap                            Mind Playin' Tricks   
2059   rap                               Shattered Dreams   
2060   rap                            Bout It, Bout It II   
2061   rap                                Smooth Operator   

                                       Album_cover_link           Artist  \
1136  https://i.scdn.co/image/ab67616d0000b2738a3119...   French Montana   
1137  https://i.scdn.co/image/ab67616d0000b273716d71...        Meek Mill   
1138  https://i.scdn.co/image/ab67616d0000b2736e4366...       Gucci Mane   
1139  https://i.scdn.co/image/ab67616d0000b273d79cfa...        A$AP Ferg   
1140  https://i.scdn.co/image/ab67616d0000b27336977e...      ScHoolboy Q   
...                                                 ...              ...   
2057  https://i.scdn.co/image/ab67616d0000b2736aafb0...            Jaden   
2058  https://i.scdn.co/image/ab67616d0000b273267514...        Geto Boys   
2059  https://i.scdn.co/image/ab67616d0000b2732b688a...  Earl Sweatshirt   
2060  https://i.scdn.co/image/ab67616d0000b273ff6769...         Master P   
2061  https://i.scdn.co/image/ab67616d0000b27375f766...   Big Daddy Kane   

      duration_ms  explicit                      id  popularity release_date  \
1136       233901      True  3B54sVLJ402zGa6Xm4YGNe          81   2017-07-14   
1137       161052      True  3T9BKc4kB7ukeNQrCqv6ZV          70   2021-10-01   
1138       203161      True  2G1tXoGBaEMJ7FKGnkf6ud          70   2018-12-07   
1139       173600      True  4dVpf9jZjcORqGTLUaeYj9          75   2017-08-18   
1140       299960      True  0zO8ctW0UiuOefR87OeJOZ          82   2014-01-01   
...           ...       ...                     ...         ...          ...   
2057       468168      True  2jdw2tc29bqJwToyGvKgJm          67   2017-11-17   
2058       148053      True  3myrzRJNm3fOLWliErE7GF          44   2013-08-15   
2059       141000      True  2LQb3iYBzoxbxct2IexjBc          60   2018-11-30   
2060       308973      True  2ohf5urBpT8bieYr8kq3kt          48         1996   
2061       284466     False  1Z4mVNtYGnpjHUoZVo3IMU          50         1989   

     release_date_precision  ...  key  loudness  mode  speechiness  \
1136                    day  ...    6    -5.043     1       0.1230   
1137                    day  ...    1    -5.585     1       0.0385   
1138                    day  ...    4    -5.144     0       0.0485   
1139                    day  ...   11    -5.482     1       0.2750   
1140                    day  ...   11    -4.870     1       0.0633   
...                     ...  ...  ...       ...   ...          ...   
2057                    day  ...    1    -6.809     0       0.0631   
2058                    day  ...   10    -8.640     0       0.2380   
2059                    day  ...   11    -4.773     0       0.1570   
2060                   year  ...    6    -6.339     1       0.3160   
2061                   year  ...    4   -16.099     0       0.3330   

      acousticness  instrumentalness  liveness  valence    tempo  \
1136       0.02930          0.010100    0.1040    0.733   97.985   
1137       0.00383          0.000000    0.1390    0.183  151.951   
1138       0.00381          0.000000    0.3670    0.367  143.010   
1139       0.06510          0.000000    0.0870    0.520  170.142   
1140       0.02500          0.000010    0.2050    0.650  153.954   
...            ...               ...       ...      ...      ...   
2057       0.38400          0.000437    0.1290    0.174  129.904   
2058       0.

rock


Genre                                              Title  \
0     rock                                       Baba O'Riley   
1     rock                                More Than a Feeling   
2     rock                            (Don't Fear) The Reaper   
3     rock                               Jump - 2015 Remaster   
4     rock                      Stairway to Heaven - Remaster   
...    ...                                                ...   
1131  rock                                    Bring The Noise   
1132  rock                                    Walk Idiot Walk   
1133  rock                                       Spanish Moon   
1134  rock  (What's So Funny 'Bout) Peace, Love And Unders...   
1135  rock          I Don't Believe In Love - Remastered 2003   

                                       Album_cover_link  \
0     https://i.scdn.co/image/ab67616d0000b273fe24dc...   
1     https://i.scdn.co/image/ab67616d0000b27390ef97...   
2     https://i.scdn.co/image/ab67616d0000b2733ac318...   
3     https://i.scdn.co/image/ab67616d0000b273b414c6...   
4     https://i.scdn.co/image/ab67616d0000b273c8a11e...   
...                                                 ...   
1131  https://i.scdn.co/image/ab67616d0000b273ba9ef4...   
1132  https://i.scdn.co/image/ab67616d0000b27368fb48...   
1133  https://i.scdn.co/image/ab67616d0000b2732eeed8...   
1134  https://i.scdn.co/image/ab67616d0000b273d94c45...   
1135  https://i.scdn.co/image/ab67616d0000b273dcd005...   

                                Artist  duration_ms  explicit  \
0                              The Who       300400     False   
1                               Boston       285133     False   
2                     Blue Öyster Cult       308120     False   
3                            Van Halen       241599     False   
4                         Led Zeppelin       482830     False   
...                                ...          ...       ...   
1131                           Anthrax       211786     False   
1132                         The Hives       211813     False   
1133                       Little Feat       186266     False   
1134  Elvis Costello & The Attractions       211630     False   
1135                       Queensrÿche       263560     False   

                          id  popularity release_date release_date_precision  \
0     3qiyyUfYe7CRYLucrPmulD          75   1971-08-14                    day   
1     1QEEqeFIZktqIpPI4jSVSF          78         1976                   year   
2     5QTxFnGygVM4jFQiBovmRo          76         1976                   year   
3     7N3PAbqfTjSEU1edb2tY8j          78   1984-01-04                    day   
4     5CQ30WqJwcep0pYcV4AMNc          79   1971-11-08                    day   
...                      ...         ...          ...                    ...   
1131  1p50Ir1Hm6Sa1urjaLGi7L          55   1991-01-01                    day   
1132  5Pdd4QCr0rREXM03zBM2Eh          61   2004-01-01                    day   
1133  24eRthJ3VWBI7B9cuFBdMG          53         1974                   year   
1134  77XzsYwTkvLoveW01Lanrk          52   2020-11-06                    day   
1135  0U2TocFjqul3sis3sE5jZl          54         1988                   year   

      ...  key  loudness  mode  speechiness  acousticness  instrumentalness  \
0     ...    5    -8.367     1       0.0352      0.313000          0.185000   
1     ...    7    -8.039     1       0.0298      0.000880          0.002300   
2     ...    9    -8.550     0       0.0733      0.002900          0.000208   
3     ...    0    -6.219     1       0.0317      0.171000          0.000377   
4     ...    9   -12.049     0       0.0339      0.580000          0.003200   
...   ...  ...       ...   ...          ...           ...               ...   
1131  ...    2    -8.582     1       0.1700      0.000860          0.000000   
1132  ...    9    -3.934     1       0.1030      0.003860          0.005750   
1133  ...   11   -15.678     1       0.0828      0.421000     

In [7]:
songs["Genre"].value_counts()
print(songs.columns.tolist())

['Genre', 'Title', 'Album_cover_link', 'Artist', 'duration_ms', 'explicit', 'id', 'popularity', 'release_date', 'release_date_precision', 'total_tracks', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature']


In [8]:
# radsej songy prenacitam znova lebo to grupovanie potom robilo problemy
songs = pd.read_excel("spotify_genre_final.xlsx")
songs_clean = songs.drop(columns=['Title', 'Album_cover_link', 'id', 'release_date', 'release_date_precision'])
songs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6917 entries, 0 to 6916
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Genre             6917 non-null   object 
 1   Artist            6917 non-null   object 
 2   duration_ms       6917 non-null   int64  
 3   explicit          6917 non-null   bool   
 4   popularity        6917 non-null   int64  
 5   total_tracks      6917 non-null   int64  
 6   danceability      6917 non-null   float64
 7   energy            6917 non-null   float64
 8   key               6917 non-null   int64  
 9   loudness          6917 non-null   float64
 10  mode              6917 non-null   int64  
 11  speechiness       6917 non-null   float64
 12  acousticness      6917 non-null   float64
 13  instrumentalness  6917 non-null   float64
 14  liveness          6917 non-null   float64
 15  valence           6917 non-null   float64
 16  tempo             6917 non-null   float64


In [9]:
genre_categories = CategoricalDtype(genres)
songs_clean['GenreInt'] = songs_clean['Genre'].astype(genre_categories).cat.codes
songs_clean['GenreInt'].value_counts()

3    1161
6    1136
2    1036
1     971
0     956
5     926
4     731
Name: GenreInt, dtype: int64

In [10]:
artist_categories = CategoricalDtype(artists)
songs_clean['ArtistInt'] = songs_clean['Artist'].astype(artist_categories).cat.codes
songs_clean['ArtistInt'].value_counts()

2762    8
2418    8
851     7
1534    7
1963    7
       ..
1850    1
421     1
2468    1
417     1
0       1
Name: ArtistInt, Length: 2912, dtype: int64

In [11]:
songs_clean['explicit'] = songs_clean['explicit'].astype(int)
songs_clean['explicit'].value_counts()

0    4719
1    2198
Name: explicit, dtype: int64

In [12]:
songs_clean = songs_clean.drop(columns=['Artist', 'Genre'])
songs_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6917 entries, 0 to 6916
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   duration_ms       6917 non-null   int64  
 1   explicit          6917 non-null   int64  
 2   popularity        6917 non-null   int64  
 3   total_tracks      6917 non-null   int64  
 4   danceability      6917 non-null   float64
 5   energy            6917 non-null   float64
 6   key               6917 non-null   int64  
 7   loudness          6917 non-null   float64
 8   mode              6917 non-null   int64  
 9   speechiness       6917 non-null   float64
 10  acousticness      6917 non-null   float64
 11  instrumentalness  6917 non-null   float64
 12  liveness          6917 non-null   float64
 13  valence           6917 non-null   float64
 14  tempo             6917 non-null   float64
 15  time_signature    6917 non-null   int64  
 16  GenreInt          6917 non-null   int8   


transformace dat je tady imo spatne, min neni vzdy 0.
Pouzil bych nejaky sklearn scaler

In [13]:
target_column = ['GenreInt'] 
predictors = list(set(list(songs_clean.columns)) - set(target_column))

songs_clean[predictors] = songs_clean[predictors]/songs_clean[predictors].max()
display(songs_clean[predictors].describe())

X = songs_clean[predictors].values
y = songs_clean[target_column].values.ravel()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)
print("X_train.shape", X_train.shape)
print("y_train.shape", y_train.shape)
print("X_test.shape",X_test.shape)
print("y_test.shape",y_test.shape)

acousticness     explicit  duration_ms    ArtistInt         mode  \
count   6917.000000  6917.000000  6917.000000  6917.000000  6917.000000   
mean       0.181897     0.317768     0.389266     0.496170     0.584357   
std        0.217878     0.465642     0.091833     0.288310     0.492868   
min        0.000002     0.000000     0.203033     0.000000     0.000000   
25%        0.020753     0.000000     0.326970     0.245620     0.000000   
50%        0.089522     0.000000     0.378123     0.493645     1.000000   
75%        0.265514     1.000000     0.439169     0.744074     1.000000   
max        1.000000     1.000000     1.000000     1.000000     1.000000   

       time_signature  total_tracks          key      valence       energy  \
count     6917.000000   6917.000000  6917.000000  6917.000000  6917.000000   
mean         0.794506      0.094244     0.486259     0.546303     0.681577   
std          0.049449      0.066152     0.328864     0.236827     0.174172   
min          0.200000      0.008000     0.000000     0.026396     0.084970   
25%          0.800000      0.064000     0.181818     0.361421     0.563126   
50%          0.800000      0.096000     0.545455     0.554315     0.697395   
75%          0.800000      0.128000     0.727273     0.739086     0.819639   
max          1.000000      1.000000     1.000000     1.000000     1.000000   

          liveness  danceability     loudness  speechiness        tempo  \
count  6917.000000   6917.000000  6917.000000  6917.000000  6917.000000   
mean      0.188331      0.674514    -7.660527     0.278775     0.560845   
std       0.150934      0.154276     3.170648     0.241636     0.130897   
min       0.013892      0.144456   -23.424829     0.056140     0.243640   
25%       0.093565      0.571719    -9.300683     0.101754     0.451214   
50%       0.127681      0.690743    -7.127563     0.161654     0.560729   
75%       0.241062      0.788403    -5.452164     0.393484     0.635575   
max       1.000000      1.000000     1.000000     1.000000     1.000000   

        popularity  instrumentalness  
count  6917.000000       6917.000000  
mean      0.604915          0.035748  
std       0.129447          0.142486  
min       0.000000          0.000000  
25%       0.530000          0.000000  
50%       0.620000          0.000002  
75%       0.690000          0.000483  
max       1.000000          1.000000

X_train.shape (5533, 17)
y_train.shape (5533,)
X_test.shape (1384, 17)
y_test.shape (1384,)


In [14]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import itertools

params = {'activation': ['tanh', 'logistic', 'relu'],
          'hidden_layer_sizes':list(itertools.permutations([10,20,50, 100, 200],2))+ [10, 20, 30, 50],
          'solver': ['adam','lbfgs'],
         }

params = {'activation': ['relu'],
          'hidden_layer_sizes':list(itertools.permutations([10,20],2)),
          'solver': ['adam'],
         }
print(params)

mlp = GridSearchCV(MLPClassifier(random_state=123,max_iter=1000, solver='adam'), param_grid=params, n_jobs=-1, cv=5, verbose=5)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)
print('Report: ', classification_report(y_test,predict_test))
print('Best Parameters : ', mlp.best_params_)

{'activation': ['relu'], 'hidden_layer_sizes': [(10, 20), (20, 10)], 'solver': ['adam']}
Fitting 5 folds for each of 2 candidates, totalling 10 fits
Report:                precision    recall  f1-score   support

           0       0.75      0.70      0.72       188
           1       0.49      0.54      0.51       192
           2       0.46      0.49      0.47       201
           3       0.50      0.49      0.50       238
           4       0.38      0.26      0.31       137
           5       0.47      0.49      0.48       194
           6       0.68      0.73      0.70       234

    accuracy                           0.54      1384
   macro avg       0.53      0.53      0.53      1384
weighted avg       0.54      0.54      0.54      1384

Best Parameters :  {'activation': 'relu', 'hidden_layer_sizes': (10, 20), 'solver': 'adam'}


In [15]:

print(confusion_matrix(y_train,predict_train))

[[551  10  46  99   9  11  42]
 [  5 417  50  45  42 208  12]
 [ 18  44 482 115  44  28 104]
 [ 65  11  90 527  46  89  95]
 [ 10  51 143  91 159  89  51]
 [  6 238  22  79  23 352  12]
 [ 28   8  65  77  11   4 709]]


In [17]:
# from imblearn.over_sampling import SMOTE
# from imblearn.under_sampling import RandomUnderSampler
# from imblearn.pipeline import Pipeline, make_pipeline

In [18]:
from sklearn.utils import class_weight
class_weight = class_weight.compute_class_weight(class_weight='balanced',
                                                 classes=np.unique(y_test),
                                                 y=y_test)
class_weight

array([1.05167173, 1.0297619 , 0.98365316, 0.83073229, 1.44316997,
       1.0191458 , 0.84493284])

In [41]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import itertools

params = {'activation': ['tanh', 'logistic', 'relu'],
          'hidden_layer_sizes':list(itertools.permutations([10,20,50, 100, 200],2))+ [10, 20, 30, 50],
          'solver': ['adam','lbfgs'],
         }

params = {'activation': ['relu'],
          'hidden_layer_sizes':list(itertools.permutations([10,20],2)),
          'solver': ['adam'],
         }
print(params)
# , class_weight=class_weight
mlp = GridSearchCV(MLPClassifier(random_state=123,max_iter=1000, solver='adam'), param_grid=params, n_jobs=-1, cv=5, verbose=5)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)
print('Report: ', classification_report(y_test,predict_test))
print('Best Parameters : ', mlp.best_params_)

{'activation': ['relu'], 'hidden_layer_sizes': [(10, 20), (20, 10)], 'solver': ['adam']}
Fitting 5 folds for each of 2 candidates, totalling 10 fits
Report:                precision    recall  f1-score   support

           0       0.75      0.70      0.72       188
           1       0.49      0.54      0.51       192
           2       0.46      0.49      0.47       201
           3       0.50      0.49      0.50       238
           4       0.38      0.26      0.31       137
           5       0.47      0.49      0.48       194
           6       0.68      0.73      0.70       234

    accuracy                           0.54      1384
   macro avg       0.53      0.53      0.53      1384
weighted avg       0.54      0.54      0.54      1384

Best Parameters :  {'activation': 'relu', 'hidden_layer_sizes': (10, 20), 'solver': 'adam'}


In [ ]:
y_test[0]

6

In [23]:
mlp.best_estimator_.score(X=X_test, y=y_test, sample_weight=class_weight[y_test])

0.5294475906913857

In [24]:
print(confusion_matrix(y_train,predict_train))


[[551  10  46  99   9  11  42]
 [  5 417  50  45  42 208  12]
 [ 18  44 482 115  44  28 104]
 [ 65  11  90 527  46  89  95]
 [ 10  51 143  91 159  89  51]
 [  6 238  22  79  23 352  12]
 [ 28   8  65  77  11   4 709]]


In [33]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler()  
# Don't cheat - fit only on training data
scaler.fit(X_train)  
X_train_scaled = scaler.transform(X_train)
# apply same transformation to test data
X_test_scaled = scaler.transform(X_test)  

In [34]:
X_train_scaled.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

In [40]:
X_train_scaled.max()

13.771323424508234

In [42]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV
import itertools

params = {'activation': ['tanh', 'logistic', 'relu'],
          'hidden_layer_sizes':list(itertools.permutations([10,20,50, 100, 200],2))+ [10, 20, 30, 50],
          'solver': ['adam','lbfgs'],
         }

params = {'activation': ['relu'],
          'hidden_layer_sizes':list(itertools.permutations([10,20],2)),
          'solver': ['adam'],
         }
print(params)
# , class_weight=class_weight
mlp = GridSearchCV(MLPClassifier(random_state=123,max_iter=1000, solver='adam'), param_grid=params, n_jobs=-1, cv=5, verbose=5)
mlp.fit(X_train_scaled,y_train)

predict_train = mlp.predict(X_train_scaled)
predict_test = mlp.predict(X_test_scaled)
print('Report: ', classification_report(y_test,predict_test))
print('Best Parameters : ', mlp.best_params_)

{'activation': ['relu'], 'hidden_layer_sizes': [(10, 20), (20, 10)], 'solver': ['adam']}
Fitting 5 folds for each of 2 candidates, totalling 10 fits
Report:                precision    recall  f1-score   support

           0       0.77      0.80      0.78       188
           1       0.51      0.54      0.52       192
           2       0.52      0.52      0.52       201
           3       0.56      0.51      0.54       238
           4       0.44      0.44      0.44       137
           5       0.50      0.50      0.50       194
           6       0.72      0.73      0.72       234

    accuracy                           0.58      1384
   macro avg       0.57      0.58      0.58      1384
weighted avg       0.58      0.58      0.58      1384

Best Parameters :  {'activation': 'relu', 'hidden_layer_sizes': (10, 20), 'solver': 'adam'}


In [43]:
print(confusion_matrix(y_train,predict_train))


[[597   4  27  75  17   8  40]
 [  3 450  36  31  51 201   7]
 [ 18  33 532  84  62  34  72]
 [ 91   6  74 528  60  90  74]
 [ 12  53  76  89 275  63  26]
 [  8 239  21  53  45 362   4]
 [ 30   7  56  62  20   5 722]]


In [45]:
mlp.best_estimator_.score(X=X_test_scaled, y=y_test, sample_weight=class_weight[y_test])

0.5768641729465653

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=5dbf8dab-f1d9-40b3-bdba-bfa490588cc7' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>